### ISSUE TITLE
Parse fail with "ValueError: invalid literal for int() with base 10: '0x0'"

### ISSUE THREAD

**Issue by tuhaolam** [recap-build/proto-schema-parser#20]
```
>>> result = Parser().parse(content)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/parser.py", line 264, in parse
    return visitor.visit(parse_tree)  # pyright: ignore [reportGeneralTypeIssues]
  File "/data/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParser.py", line 604, in accept
    return visitor.visitFile(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/parser.py", line 18, in visitFile
    file_elements = [self.visit(child) for child in ctx.fileElement()]
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/parser.py", line 18, in <listcomp>
    file_elements = [self.visit(child) for child in ctx.fileElement()]
  File "/data/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParser.py", line 711, in accept
    return visitor.visitFileElement(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParserVisitor.py", line 19, in visitFileElement
    return self.visitChildren(ctx)
  File "/data/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParser.py", line 4116, in accept
    return visitor.visitMessageDecl(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/parser.py", line 41, in visitMessageDecl
    elements = [self.visit(child) for child in ctx.messageElement()]
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/parser.py", line 41, in <listcomp>
    elements = [self.visit(child) for child in ctx.messageElement()]
  File "/data/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParser.py", line 4273, in accept
    return visitor.visitMessageElement(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParserVisitor.py", line 254, in visitMessageElement
    return self.visitChildren(ctx)
  File "/data/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParser.py", line 5976, in accept
    return visitor.visitEnumDecl(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/parser.py", line 169, in visitEnumDecl
    elements = [self.visit(child) for child in ctx.enumElement()]
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/parser.py", line 169, in <listcomp>
    elements = [self.visit(child) for child in ctx.enumElement()]
  File "/data/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
    return tree.accept(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParser.py", line 6105, in accept
    return visitor.visitEnumElement(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParserVisitor.py", line 374, in visitEnumElement
    return self.visitChildren(ctx)
  File "/data/venv/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/antlr/ProtobufParser.py", line 6198, in accept
    return visitor.visitEnumValueDecl(self)
  File "/data/venv/lib/python3.8/site-packages/proto_schema_parser/parser.py", line 174, in visitEnumValueDecl
    number = int(self._getText(ctx.enumValueNumber()))
ValueError: invalid literal for int() with base 10: '0x0'
```

**Comment by criccomini** [comment]
Hi! Can you give me the value for `content`? I can't really debug without it.

**Comment by criccomini** [comment]
Closed due to lack of engagement. Can't reproduce.
